config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :new, :create, :show] do
     resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = [ "chinese", "italian", "japanese", "french", "belgian" ]
  validates :category, inclusion: { in: CATEGORIES }
  validates :name, :address, :category, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants available</h1>
<%= link_to 'New Restaurant', new_restaurant_path %>
<ul>
  <% @restaurants.each do |restaurant| %>
  <hr>
    <li>
      <h2><%= link_to restaurant.name, restaurant_path(restaurant)%></h2>
      <p><%= restaurant.category.capitalize %> foods</p>
      <p><%= restaurant.address %> <%= restaurant.phone_number %></p>
    </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-4">
    <div class="col-xs-8 col-sm-8">
      <%= simple_form_for @restaurant do |r| %>
        <%= r.input :name %>
        <%= r.input :address %>
        <%= r.input :category, collection: Restaurant::CATEGORIES %>
        <%= r.input :phone_number %>
        <%= r.submit 'Create new restaurant', class: 'btn btn-primary' %>
        <%= link_to 'See all restaurants', restaurants_path, class: 'ml-4'%>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-xs-8 col-sm-8">
      <h1><%= @restaurant.name %></h1>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">Address</th>
            <td><%= @restaurant.address %></td>
          </tr>
          <tr>
            <th scope="row">Phone Number</th>
            <td><%= @restaurant.phone_number %></td>
          </tr>
          <tr>
            <th scope="row">Category</th>
            <td><%= @restaurant.category %></td>
          </tr>
        </tbody>
      </table>

      <div class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fas fa-star"></i>
                <% else %>
                  <i class="far fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </div>

      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "See all restaurants", restaurants_path %>
    </div>
  </div>
</div>